### PR TITLE
i have added  pattern printing folder that can help beginners 

### PR DESCRIPTION
**Pull request by Arushisingh23**

### CODE REVIEW

**Comment by shivaamm** [comment]
Hi Thanks for your contribution!!
Can you give the question link or the pattern output for these since these are pattern questions.

**Review by shivaamm — CHANGES_REQUESTED** [review]
Question Link or Output patterns

**Comment by Arushisingh23** [comment]
oh u wanted question for each of them?

**Comment by Arushisingh23** [comment]
Alpha -ramp pattern
Right Angled number pyramid
Rectangular Star pattern
Hollow square
Hollow triangle
Hollow rectangle
Increasing letter triangle pattern
Increasing the number of triangle pattern
Inverted right pyramid 
Triangle print

**Pull request closed without merging**
